name = "my-homepage-worker"
main = "worker.js"
compatibility_date = "2026-01-12"
workers_dev = true
account_id = "53009350329b4c0b9b99c911943e09f8"

# 绑定 KV Namespace
[[kv_namespaces]]
binding = "MY_HOME_KV"
id = "53009350329b4c0b9b99c911943e09f8"

